# Toolchain file for ARM GCC bare-metal cross-compilation

if(DEFINED ARM_TOOLCHAIN_PATH AND NOT ARM_TOOLCHAIN_PATH STREQUAL "")
    set(CMAKE_FIND_ROOT_PATH "${ARM_TOOLCHAIN_PATH}")
    message("Using ARM_TOOLCHAIN_PATH given with cmake settings -DARM_TOOLCHAIN_PATH=${ARM_TOOLCHAIN_PATH}")
elseif(DEFINED ENV{ARM_TOOLCHAIN_PATH} AND NOT ENV{ARM_TOOLCHAIN_PATH} STREQUAL "")
    message("Using ARM_TOOLCHAIN_PATH defined in environment: $ENV{ARM_TOOLCHAIN_PATH}")
    set(CMAKE_FIND_ROOT_PATH $ENV{ARM_TOOLCHAIN_PATH})
elseif(DEFINED ENV{ARM_GCC_TOOLCHAIN_PATH} AND NOT ENV{ARM_GCC_TOOLCHAIN_PATH} STREQUAL "")
    message("Using ARM_TOOLCHAIN_PATH defined in environment: $ENV{ARM_GCC_TOOLCHAIN_PATH}")
    set(CMAKE_FIND_ROOT_PATH $ENV{ARM_GCC_TOOLCHAIN_PATH})
else()
    message(FATAL_ERROR "Toolchain path not defined. Please set ARM_TOOLCHAIN_PATH to the toolchain bin folder")
endif()

if(NOT EXISTS "${CMAKE_FIND_ROOT_PATH}" OR NOT IS_DIRECTORY "${CMAKE_FIND_ROOT_PATH}")
    message(FATAL_ERROR "Toolchain path does not exist: ${CMAKE_FIND_ROOT_PATH}")
endif()

set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR arm)

set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

if(CMAKE_HOST_WIN32)
    set(BINARY_FILE_EXT ".exe")
else()
    set(BINARY_FILE_EXT "")
endif()

set(TARGET_TRIPLE arm-none-eabi)

set(CMAKE_C_COMPILER   "${CMAKE_FIND_ROOT_PATH}/${TARGET_TRIPLE}-gcc${BINARY_FILE_EXT}"   CACHE STRING "C Compiler")
set(CMAKE_CXX_COMPILER "${CMAKE_FIND_ROOT_PATH}/${TARGET_TRIPLE}-g++${BINARY_FILE_EXT}"   CACHE STRING "C++ Compiler")
set(CMAKE_ASM_COMPILER "${CMAKE_FIND_ROOT_PATH}/${TARGET_TRIPLE}-gcc${BINARY_FILE_EXT}"   CACHE STRING "ASM Compiler")
